---
kind: pipeline
type: docker
name: integration-tests

global-variables:
  environment: &default_environment
    GOPATH:     "/go"
    GOCACHE:    "/go/.cache/go-build"
    GOENV:      "/go/.config/go/env"
    GOMODCACHE: "/go/pkg/mod"
steps:
  - name: pull
    image: omerxx/drone-ecr-auth
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
  - name: build
    image: golang:1.16
    environment:
      <<: *default_environment
    commands:
      - make install
      - go get ./...
    volumes:
      - name: go
        path: /go
  - name: baseline
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/baseline
      - make test
  - name: version
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/version
      - make test
  - name: rollback
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/rollback
      - make test
  - name: outdated
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/outdated-pkgs
      - make test
  - name: load
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/load
      - make test
  - name: multi-repo
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/multi-repo
      - make test
  - name: bad-customization
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/bad-customization
      - make test
  - name: recommended-packages
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/recommended
      - make test
  - name: rpath-env-var
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/env-vars
      - make test
  - name: tarball-install
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/tarball-install
      - make test
  - name: libraries
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/library
      - make test
  - name: mixed-source-and-customizations
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/mixed-source
      - make test
volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock
  - name: go
    temp: { }
